### ISSUE TITLE
🐛  Inability to access proprietor page

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/palni_palci_knapsack#105]
# Summary

Nic [reported](https://assaydepot.slack.com/archives/C0313NK4SMS/p1721142475981649) that staging users cannot access the proprietor page without error. 

# Acceptance Criteria

- [ ] A user should be able to access to proprietor page: https://palni-palci-staging.notch8.cloud/

# Screenshots or Video

![Image](https://github.com/user-attachments/assets/9282a08f-719f-46b4-886f-d3d7bfb3e795)

# Testing Instructions
- visit https://palni-palci-staging.notch8.cloud/

# Notes

**Comment by laritakr** [comment]
No longer an issue
