### ISSUE TITLE
🐛 blacklight range limit

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/palni_palci_knapsack#108]
# Summary

[ref](https://assaydepot.slack.com/archives/C0311DNF3MG/p1721670157757579)

![Image](https://github.com/user-attachments/assets/106c4d20-7e58-4cee-8489-b6db0e5f3ab9)

# Acceptance Criteria

- [ ]

# Screenshots or Video

# Testing Instructions

# Notes

**Comment by jillpe** [comment]
verify if this is still an issue
