### ISSUE TITLE
🐛 Theme errors prevent users from visiting tenant homepage

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/palni_palci_knapsack#129]
# Summary

For some tenants, visiting their home page results in a "something went wrong" error page. The logs are pointing to an issue with themes. 

The error appears to be occurring for all homepage themes except for institutional repository, when testing with the [demo tenant](https://demo.palni-palci-staging.notch8.cloud/)

![Image](https://github.com/user-attachments/assets/15ed5d63-6672-4858-82a2-2064e3153d91)

# Acceptance Criteria

- [ ] A user should be able to visit the tenant home page for all of the homepage themes
  - [ ] Default
  - [ ] Cultural
  - [ ] Institutional
  - [ ] Neutral

# Screenshots or Video

![Image](https://github.com/user-attachments/assets/80283739-11a7-4c97-8d2d-ec0489990dec)

# Testing Instructions

In [staging](https://demo.palni-palci-staging.notch8.cloud/admin/appearance?locale=en#themes), change the home page themes in the admin dashboard appearance settings.

# Notes

[slack notes](https://assaydepot.slack.com/archives/C0311DNF3MG/p1725045775057009)

server log: 

![Image](https://github.com/user-attachments/assets/bfaee106-5046-4147-b411-92acc37e9aa0)

**Comment by jillpe** [comment]
related to #40

**Comment by ShanaLMoore** [comment]
This seems to be something that deals with active fedora works being featured.

**Comment by ShanaLMoore** [comment]
# todo

in staging, find the following works. convert them into valkyrie resources. does the problem still exist?

 ["b6a4ad0a-845e-4343-bd25-c97bc8dc0001", "4d75c79b-8263-4d6d-9a5e-647c7ab0c731", "a0e1a795-a41a-40e8-81e0-6565634ad174"]

**Comment by laritakr** [comment]
The second work in the featured works list had bad data. I could not access it through the UI, so I deleted it from ActiveFedora and from the FeaturedWork table. The homepage now loads.
![Screenshot 2024-09-03 at 3 53 52 PM](https://github.com/user-attachments/assets/26a8b774-fdb4-4ac7-ae01-84f35fb4b6af)
![Screenshot 2024-09-03 at 4 53 05 PM](https://github.com/user-attachments/assets/a8131306-704c-4d38-a752-b51bd2635c10)

**Comment by laritakr** [comment]
Nic confirmed that he did not see this behavior in any other tenant.
