### ISSUE TITLE
Imported tenant data

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni_palci_knapsack#132]
## Summary
Slack threads: 
- https://assaydepot.slack.com/archives/C0313NKC08L/p1724856763229639
- https://assaydepot.slack.com/archives/C0313NKG2DA/p1724856963961149

There are several issues that have been observed with the production tenant data that was imported into pals knapsack staging. Issues observed:
- missing thumbnails
- mislabeled fields
- timeout errors when logging into the imported tenants
- [records in knapsack staging still link to the hykucommons show page](https://assaydepot.slack.com/archives/C0313NKG2DA/p1724860488776519?thread_ts=1724856963.961149&cid=C0313NKG2DA)

Pals would also like their tenants to review the data before proceeding with the cutover. To do that, it would be ideal to have the latest version of hykucommons imported for that

## Acceptance Criteria
- [ ] The imported tenant data reflects the latest HykuCommons state

**Comment by orangewolf** [comment]
https://au-archives.palni-palci-staging.notch8.cloud/collections/9cd8a1b8-107c-4b4b-b36d-3c334744b0be?locale=en
timeout errors when logging in
