### ISSUE TITLE
Funky looking buttons in UI

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/palni_palci_knapsack#139]
# Summary

The buttons are looking funny in staging when using certain themes.

[LINK](https://demo.palni-palci-staging.notch8.cloud/concern/generic_works/1d0950c4-b899-47ce-b65e-75746097ba1f?locale=en)

<details> 

![Image](https://github.com/user-attachments/assets/d15f2d80-012e-4cda-83e0-5aa1b74ca912)

![Image](https://github.com/user-attachments/assets/e94b4c37-a946-4470-8a6e-1363d23f265c)

</details>

### DEFAULT THEME buttons looks more correct

![Image](https://github.com/user-attachments/assets/7c352b23-fe08-4ac0-86f6-125d5ef19f07)

# Acceptance Criteria

- [ ] The buttons should look reasonable and match what the theme preview portrays

# Screenshots or Video

# Testing Instructions

To be filled out by dev

# Notes

**Comment by laritakr** [comment]
Closing - will be handled via https://github.com/scientist-softserv/palni_palci_knapsack/issues/170
