### ISSUE TITLE
Theme: List View Search Results

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni_palci_knapsack#144]
## Summary
There are some discrepancies between the Search Results List View in Knapsack versus HykuCommons:
- Items do not have properly styled metadata
  - Collections' counts are incorrectly positioned
  - metadata is positioned too close in proximity to thumbnail

### [Knapsack](https://demo.palni-palci-staging.notch8.cloud/catalog?locale=en&q=&search_field=all_fields&utf8=%E2%9C%93&view=list)

https://github.com/user-attachments/assets/3de0b894-1170-44c7-af2b-23ff62bf74a7

### [HykuCommons](https://demo.hykucommons.org/catalog?locale=en&q=&search_field=all_fields&utf8=%E2%9C%93&view=list)

https://github.com/user-attachments/assets/5505583e-9ac5-4568-ab49-517f350f20f7

## Acceptance Criteria
- [ ] Items and their metadata fit in the container list view container
  - [ ] Collections counts are positioned like HykuCommons
  - [ ] Metadata is positioned like HykuCommons

**Comment by laritakr** [comment]
Closing ticket as layout has changed after updates. Any remaining issues should be handled by https://github.com/scientist-softserv/palni_palci_knapsack/issues/173
