### ISSUE TITLE
Theme: Default Show Page (UV)

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni_palci_knapsack#150]
## Summary
Discrepancies between Knapsack and HykuCommons
- 'Add to collection', 'Feature', 'Analytics', 'Edit', 'Attach Child', 'Delete' buttons do not match HykuCommons styling
- Childworks display in the items section and should not in Knapsack. HykuCommons only shows the parent item

### [Knapsack](https://demo.palni-palci-staging.notch8.cloud/concern/etds/cb6c9040-98c2-49c2-81f1-88cee1fa7b79)

https://github.com/user-attachments/assets/e05e474a-048d-4cec-84ab-2baca68f39a8

### [HykuCommons](https://demo.hykucommons.org/concern/generic_works/4d75c79b-8263-4d6d-9a5e-647c7ab0c731)

https://github.com/user-attachments/assets/39aa3b4b-2e09-4a9f-a543-8c548956de6a

## Acceptance Criteria
- [ ] 'Add to collection', 'Feature', 'Analytics', 'Edit', 'Attach Child', 'Delete' buttons matches HykuCommons styling
- [ ] Childworks do not display in the items section

**Comment by jillpe** [comment]
resolved in #152 and #153

**Comment by laritakr** [comment]
Closing - should be handled in https://github.com/scientist-softserv/palni_palci_knapsack/issues/177
