### ISSUE TITLE
Theme: Cultural Show Page (thumbnail only)

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni_palci_knapsack#151]
## Summary
Discrepancies between Knapsack and HykuCommons
- 'Add to collection', 'Feature', 'Analytics', 'Edit', 'Attach Child', 'Delete' buttons do not match HykuCommons styling
- Responsiveness: The relations section is very small

### [Knapsack](https://demo.palni-palci-staging.notch8.cloud/concern/etds/d6409a46-dbfd-4485-8e9b-366c7ad029ed)

https://github.com/user-attachments/assets/596bf8eb-1d47-49f4-a500-8a446d89e5ba

### [HykuCommons](https://demo.hykucommons.org/concern/etds/b6a4ad0a-845e-4343-bd25-c97bc8dc0001)

https://github.com/user-attachments/assets/ccad8ad5-5bdf-4b1c-ade0-3eca80d57f9f

## Acceptance Criteria
- [ ] Add to collection', 'Feature', 'Analytics', 'Edit', 'Attach Child', 'Delete' buttons match HykuCommons styling
- [ ] Knapsack is responsive and the Relations section matches the responsiveness of HykuCommons

**Comment by laritakr** [comment]
Closing - should be handled in https://github.com/scientist-softserv/palni_palci_knapsack/issues/177
