### ISSUE TITLE
Show Page Buttons

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni_palci_knapsack#152]
## Summary
In every theme and for a UV show page or thumbnail show page, the 'Add collection', 'Feature', 'Analytics', 'Edit', 'File Manager', 'Attach Child', 'Delete' buttons do not match the HykuCommons styling. See Screeshots

### Knapsack
![Image](https://github.com/user-attachments/assets/f6dae909-b2b8-4bb1-b656-74f0207ad8dc)

### HykuCommons
![Image](https://github.com/user-attachments/assets/9411f1a3-8478-40b2-a213-ec5682237807)

### Acceptance Criteria
- [ ] 'Add collection', 'Feature', 'Analytics', 'Edit', 'File Manager', 'Attach Child', 'Delete' buttons match the HykuCommons styling for in every them and for every show page

**Comment by laritakr** [comment]
Closing - should be handled in https://github.com/scientist-softserv/palni_palci_knapsack/issues/177
