### ISSUE TITLE
🐛 Can't add works to collections

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/palni_palci_knapsack#27]
# Summary

When you try to add a work to a collection, either from the work index page or from the collection, ultimately it'll work but you're first met with a 500 error page. 

![Image](https://github.com/scientist-softserv/palni_palci_knapsack/assets/10081604/0064b98a-38fd-489f-98d5-1149a454d51e)

## Acceptance Criteria
-  [ ] a user should be able to add works to collections, without errors. 

# Testing Instructions
## FROM THE WORKS
Go to [staging](https://demo.palni-palci-staging.notch8.cloud/dashboard/my/works?locale=en)
Create a work
Go back to the work index page and click the checkbox next to the work. Click "Add to collections" 
Type the name of the collection and Save Changes. 

## FROM THE COLLECTION
Go to [staging](https://demo.palni-palci-staging.notch8.cloud/dashboard/my/collections?locale=en)
Create a Collection
Go to the collection's show page and click add existing works to this collection.
Select the works and add to collection.

**Comment by ShanaLMoore** [comment]
Update: For some reason this seems only to be happening when you try to add to the dogs collection 🤔

**Comment by laritakr** [comment]
Closing - unable to duplicate as dogs collection isn't there.
