### ISSUE TITLE
:comet: Epic 4: Move Pals to Valkyrie

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni_palci_knapsack#3]
ref: 
- [x] https://github.com/scientist-softserv/hykuup_knapsack/issues/35

To Do:
- [x] #12

**Comment by ShanaLMoore** [comment]
this work has not been approved yet

**Comment by ShanaLMoore** [comment]
This will be completed when we move them to knapsack

ref: 
- #2
