### ISSUE TITLE
Global Index Institution Page - Partner Repository logos are not present

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni_palci_knapsack#34]
## Summary
Partner repositories should be present on the [global index institution page](https://palni-palci-staging.notch8.cloud/) and link to that tenant page. This is for a logged in our logged out user. Example of what is should be is below:
https://hykucommons.org/

![image](https://github.com/scientist-softserv/palni_palci_knapsack/assets/84697174/ca1dcd5e-07d0-4846-aea0-b5c4c5fde6a5)

## Acceptance Criteria
- [ ] Partner repositories are present on the [global index institution page](https://palni-palci-staging.notch8.cloud/) and link to that tenant page when a user is logged in
- [ ] - [ ] Partner repositories are present on the [global index institution page](https://palni-palci-staging.notch8.cloud/) and link to that tenant page when a user is logged out

**Comment by laritakr** [comment]
No longer an issue
