### ISSUE TITLE
Manage Proxies - cannot search for user

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni_palci_knapsack#46]
## Summary
On the [Manage Proxies](https://demo.hykucommons.org/proxies?locale=en) page, searching for a user to by a Proxy user is not functional. I typed in the entire user email of 2 different users, and they did not show as an option.

https://github.com/scientist-softserv/palni_palci_knapsack/assets/84697174/7107f824-3b61-47c5-b22b-a3b46167ccd4

## Acceptance Criteria
- [ ] I can select a proxy user through the search for a user box by typing in the first few letters of their email

**Comment by laritakr** [comment]
no longer an issue
