### ISSUE TITLE
Collections Dashboard Page - Filters do not offer all of the options

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni_palci_knapsack#47]
## Summary
The visibility filter does not offer all of the visibility options on the [Collections dashboard page](https://demo.hykucommons.org/dashboard/my/collections?locale=en&route_set=%23%3CActionDispatch%3A%3ARouting%3A%3ARoutesProxy%3A0x00007ff0a67eb848%3E).

<img width="1110" alt="image" src="https://github.com/scientist-softserv/palni_palci_knapsack/assets/84697174/78972a79-6a3c-425f-8e0d-f0079da32881">

## Acceptance Criteria
- [ ] The visibility filter can filter by public or private options

**Comment by laritakr** [comment]
Appears to no longer be an issue.
