### ISSUE TITLE
Collection New/Edit Form - Branding is not displaying

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni_palci_knapsack#50]
## Summary
I can save branding settings for a collection, however they do not display on the collection.

**Example**
[Public Interface](https://demo.palni-palci-staging.notch8.cloud/collections/36b01b98-de55-4cf1-9328-f53c4ca05dd0?locale=en)
![image](https://github.com/scientist-softserv/palni_palci_knapsack/assets/84697174/eeb1c2c6-4bfe-4cdc-b1e8-16c9cafc62e6)

[Saved Settings](https://demo.palni-palci-staging.notch8.cloud/dashboard/collections/36b01b98-de55-4cf1-9328-f53c4ca05dd0/edit?locale=en#branding)
![image](https://github.com/scientist-softserv/palni_palci_knapsack/assets/84697174/137fa31b-b796-4294-91a2-6117c5ae4421)

This is an [example](https://demo.hykucommons.org/collections/a6c69859-842f-47a5-a567-ec71b235dda2?locale=en) of what it should resemble/

## Acceptance Criteria
- [ ] As an admin user, I can set the branding for a collection through the Edit collection form, can save it, and it displays on the public and dashboard interface

**Comment by ShanaLMoore** [comment]
Kirk to update the submodule and retest.

**Comment by ShanaLMoore** [comment]
Dupe. Test with
