### ISSUE TITLE
Custom CSS does not appear to work

### ISSUE THREAD

**Issue by laritakr** [scientist-softserv/palni_palci_knapsack#54]
As Admin:
- go to Settings/Appearance Custom CSS tab
- Enter custom CSS and save

CSS does not appear to affect anything
CSS only shows on tab if you try to enter it again

## Acceptance Criteria
- [ ] As an admin I can use the 'Custom CSS' tab to enter custom css and it saves/displays

**Comment by kirkkwang** [comment]
This seems to be working.
