### ISSUE TITLE
Content Blocks display issues

### ISSUE THREAD

**Issue by ndroark** [scientist-softserv/palni_palci_knapsack#72]
The Content Block editing page displays some tabs with errors. Tab names are not in bold. 

![Image](https://github.com/scientist-softserv/palni_palci_knapsack/assets/117871943/c7a19302-5d36-4b5f-ba37-aa729c7d778b)

**Comment by laritakr** [comment]
Duplicated by https://github.com/scientist-softserv/palni_palci_knapsack/issues/172
