### ISSUE TITLE
Front page block alignment in Neutral theme

### ISSUE THREAD

**Issue by ndroark** [scientist-softserv/palni_palci_knapsack#74]
## Summary
In the Neutral Repository theme, front page blocks all align vertically justified left instead of in the array shown on the theme preview page. 

**how it looks on hykucommons**

![Image](https://github.com/scientist-softserv/palni_palci_knapsack/assets/84697174/16f44bf6-d537-47a4-8f95-991e66cec0e8)

**how it looks on knapsack staging**

![Image](https://github.com/scientist-softserv/palni_palci_knapsack/assets/84697174/1323ce04-369b-4348-a6e1-bdbb6fe0174c)

## Acceptance Criteria
- [ ] The Neutral Repository home page theme layout on knapsack matches the neutral repository home page theme on hykucommons

**Comment by jillpe** [comment]
This is resolved in #56
